spring.datasource.url=jdbc:mysql://localhost:3306/laundry_system
spring.datasource.username=root
spring.datasource.password=@Castro1113

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080